ifeq ($(GMEPLUGIN_INCLUDED),)
GMEPLUGIN_INCLUDED = 1
THIS_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

MODULES += $(THIS_DIR)/gme
FILES += $(THIS_DIR)/GMEPlugin.cpp
INCLUDES += $(THIS_DIR) $(THIS_DIR)/../..
CFLAGS += -DBLARGG_LITTLE_ENDIAN -DHAVE_ZLIB_H 

endif
