include ../../../settings.mk

OBJDIR=obj/
TARGET=libmodplugin
EXT=.a

MODULES := modplug
OBJS := ModPlugin.o
CFLAGS := $(CFLAGS) -Wall -I$(UTILS) -Imodplug -I. -I../..

include ../../../Makefile.inc
