.\" Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.\" Please adjust this date whenever revising the manpage.
.\" 
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.TH "uadefs" "1" "2008-06-16" "Heikki Orsila" ""
.SH "NAME"
uadefs - FUSE filesystem that transparently converts Amiga songs to WAV files
.SH "SYNOPSIS"
.B uadefs
\fImusicdir\fR \fImountpoint\fR
[\fIoptions\fR]
.SH "DESCRIPTION"
.BR uadefs
mounts an Amiga music directory so that files that are transparently
converted info WAV files. This allows players without UADE plugin to
play Amiga songs.
.BR uadefs
requires
.BR FUSE .

Run 
.BR uadefs\ \-h
for help. Use
.BR fusermount\ \-f\ mountpoint
to unmount.

.SH "EXAMPLES"
.TP
To play \fB/amiga/songs/mod.foo\fR as a WAV file, run:

1. \fBmkdir -p ~/mnt/uadefs\fR
.br
2. \fBuadefs /amiga/songs ~/mnt/uadefs\fR
.br
3. \fBaplay ~/mnt/uadefs/mod.foo\fR

.SH "NOTES"
\fBuadefs is suffers from many issues:\fR

1. It is slow. For example, adding directories from uadefs to XMMS may only
add 4 songs per second. Fortunately, there are optimizations that can be
done to overcome this in the future. These methods include caching and
intelligent WAV header generation that avoids synthesizing the music stream
when the WAV plugin does file type checking.

2. It uses lots of memory. The whole song is buffered. This can be made
configurable and/or different in the future.

3. Subsong can not be changed. However, the WAV file should contain all
subsongs.

\fBFortunately, there are also benefits in uadefs:\fR

1. Any player that can play WAV files can play Amiga songs.

2. Seeking backwards in the song is possible now, as the whole song is
buffered.

\fBOther issues:\fR

1. One can safely mount files under a path that is backuped when the backup
system is not run as the user that runs uadefs. For example, if
user \fBfoo\fR runs uadefs, the \fBroot\fR user that runs the
backup program does not see the files inside the uadefs. Users
can safely do uadefs mounts in their home directories while
the system administration runs daily backup scripts.

.SH "SEE ALSO"
.BR fusermount (1)
.BR uade123 (1)

.SH "AUTHORS"
\fBuadefs\fP was written by Heikki Orsila <heikki.orsila@iki.fi>.
The code is heavily based on FUSE examples and sshfs written by
Miklos Seredi <miklos@szeredi.hu>.
