include ../../../settings.mk

OBJDIR=obj/
TARGET=libstsoundplugin
EXT=.a

MODULES := StSoundLibrary StSoundLibrary/LZH
OBJS := StSoundPlugin.o
CFLAGS := $(CFLAGS) -Wall -I. -I../..

include ../../../Makefile.inc
