
const char *adlib_formats[] = {
    "adl",
    "adlib tracker 2",
    "adlib tracker 2 (v9 - v11)",
    "adlib tracker",
    "amusic",
    "amusic xms",
    "apogee",
    "beni tracker",
    "bob's adlib music",
    "boom tracker 4.0",
    "creative music file",
    "defy adlib tracker",
    "digital fm",
    "dosbox",
    "drum traker",
    "edlib",
    "exotic adlib",
    "extra simple music",
    "faust music creator",
    "fm-kingtracker",
    "fm tracker",
    "herad music system agd",
    "herad music system sdb",
    "herad music system sqx",
    "hsc adlib composer",
    "jch-d00",
    "jch-d01",
    "johannes bjerregard module",
    "ken's adlib music",
    "loudness sound system",
    "lucasarts",
    "martin fernandez",
    "master tracker",
    "mk-jamz",
    "mlat adlib tracker",
    "mpu-401 trakker",
    "mus",
    "palladix",
    "pixel painters",
    "rdosplay raw",
    "reality adlib tracker",
    "shadowlands",
    "sierra",
    "sng player",
    "sound images generation 2",
    "sound interface system",
    "surprise! adlib tracker 2.0",
    "surprise! adlib tracker",
    "twin trackplayer",
    "ultima 6",
    "vibrants",
    "visual composer",
};

const char *uade_formats[] = {"actionamics",
                              "activision pro",
                              "aero studio",
                              "ahx",
                              "all sound tracker",
                              "am composer",
                              "anders oland",
                              "and xsynth",
                              "aprosys",
                              "arkostracker",
                              "art and magic",
                              "art of noise",
                              "asylum",
                              "atari digi-mix",
                              "athtune",
                              "audio sculpture",
                              "axs",
                              "beathoven synthesizer",
                              "beaver sweeper",
                              "beepola",
                              "ben daglish",
                              "ben daglish sid",
                              "berotracker",
                              "boyscout",
                              "bp soundmon 2",
                              "bp soundmon 3",
                              "buzz",
                              "buzzic 1.0",
                              "buzzic 1.1",
                              "buzzic 2.0",
                              "cba",
                              "composer 669",
                              "compoz",
                              "core design",
                              "cubic tiny xm",
                              "custommade",
                              "cybertracker",
                              "cybertracker c64",
                              "darius zendeh",
                              "darkwave studio",
                              "dave lowe",
                              "dave lowe new",
                              "david hanney",
                              "david whittaker",
                              "delitracker custom",
                              "delta music 2",
                              "delta music",
                              "delta packer",
                              "desire",
                              "digibooster",
                              "digibooster pro",
                              "digital-fm music",
                              "digital mugician 2",
                              "digital mugician",
                              "digital sonix and chrome",
                              "digital sound and music interface",
                              "digital sound interface kit",
                              "digital sound interface kit riff",
                              "digital sound studio",
                              "digital tracker dtm",
                              "digital tracker mod",
                              "digitrakker",
                              "digitrekker",
                              "dirk bialluch",
                              "disorder tracker 2",
                              "dreamstation",
                              "dynamic studio professional",
                              "dynamic synthesizer",
                              "earache",
                              "electronic music system",
                              "electronic music system v6",
                              "epic megagames masi",
                              "extreme tracker",
                              "face the music",
                              "famitracker",
                              "farandole composer",
                              "fashion tracker",
                              "follin player ii",
                              "forgotten worlds",
                              "fred gray",
                              "fredmon",
                              "fuchstracker",
                              "funktracker",
                              "future composer 1.3",
                              "future composer 1.4",
                              "future composer bsi",
                              "future player",
                              "game music creator",
                              "general digimusic",
                              "gluemon",
                              "goattracker 2",
                              "goattracker",
                              "goattracker stereo",
                              "graoumf tracker 2",
                              "graoumf tracker",
                              "gt game systems",
                              "hes",
                              "hippel 7v",
                              "hippel-atari",
                              "hippel-coso",
                              "hippel",
                              "hippel-st",
                              "hivelytracker",
                              "howie davies",
                              "images music system",
                              "imago orpheus",
                              "instereo! 2.0",
                              "instereo!",
                              "ixalance",
                              "jamcracker",
                              "janko mrsic-flogel",
                              "jason brooke",
                              "jason page",
                              "jason page old",
                              "jaytrax",
                              "jeroen tel",
                              "jesper olsen",
                              "ken's digital music",
                              "klystrack",
                              "kris hatlelid",
                              "kss",
                              "leggless music editor",
                              "lionheart",
                              "liquid tracker",
                              "mad tracker 2",
                              "magnetic fields packer",
                              "maniacs of noise",
                              "maniacs of noise old",
                              "mark cooksey",
                              "mark cooksey old",
                              "mark ii",
                              "maxtrax",
                              "mcmd",
                              "mdx",
                              "medley",
                              "megastation",
                              "megastation midi",
                              "megatracker",
                              "mike davies",
                              "monotone",
                              "multimedia sound",
                              "music assembler",
                              "music editor",
                              "musicline editor",
                              "musicmaker",
                              "musicmaker v8",
                              "mvs tracker",
                              "mvx module",
                              "nerdtracker 2",
                              "noisetrekker 2",
                              "noisetrekker",
                              "novotrade packer",
                              "octalyser",
                              "octamed mmd0",
                              "octamed mmd1",
                              "octamed mmd2",
                              "octamed mmd3",
                              "octamed mmdc",
                              "oktalyzer",
                              "onyx music file",
                              "organya 2",
                              "organya",
                              "paul robotham",
                              "paul shields",
                              "paul summers",
                              "peter verswyvelen",
                              "picatune2",
                              "picatune",
                              "pierre adane packer",
                              "piston collage",
                              "playerpro",
                              "pmd",
                              "pokeynoise",
                              "pollytracker",
                              "polytracker",
                              "powertracker",
                              "professional sound artists",
                              "protracker",
                              "protracker 3.6",
                              "protrekkr 2.0",
                              "protrekkr",
                              "psycle",
                              "pumatracker",
                              "quadra composer",
                              "quartet psg",
                              "quartet st",
                              "ramtracker",
                              "real tracker",
                              "renoise 1.1.1 (rns05)",
                              "renoise 1.2.7 (rns15)",
                              "renoise 1.2.8.1 (rns16)",
                              "renoise 1.5.0 (rns17)",
                              "renoise 1.5.1 (rns18)",
                              "renoise 1.8 (ver04)",
                              "renoise 1.9.1 (ver10)",
                              "renoise 1.9 (ver09)",
                              "renoise 2.0 (ver14)",
                              "renoise 2.1 (ver15)",
                              "renoise 2.5 (ver21)",
                              "renoise 2.6 (ver22)",
                              "renoise 2.7 (ver30)",
                              "renoise 2.8 (ver37)",
                              "richard joseph",
                              "riff raff",
                              "rob hubbard 2",
                              "rob hubbard",
                              "rob hubbard st",
                              "ron klaren",
                              "sam coupe cop",
                              "sam coupe sng",
                              "sbstudio",
                              "scumm",
                              "sean connolly",
                              "sean conran",
                              "shroom",
                              "sidmon 1",
                              "sidmon 2",
                              "sidplayer",
                              "silmarils",
                              "skale tracker",
                              "sonic arranger",
                              "sound club 2",
                              "sound club",
                              "soundcontrol",
                              "soundfactory",
                              "soundfx 2",
                              "soundfx",
                              "sound images",
                              "sound master ii v1",
                              "sound master ii v3",
                              "sound master",
                              "soundplayer",
                              "sound programming language",
                              "soundtracker 2.6",
                              "soundtracker pro ii",
                              "special fx",
                              "special fx st",
                              "speedy a1 system",
                              "speedy system",
                              "spu",
                              "starkos",
                              "startrekker am",
                              "stereo sidplayer",
                              "steve barrett",
                              "stonetracker",
                              "suntronic",
                              "sunvox",
                              "svar tracker",
                              "symphonie",
                              "synder sng-player",
                              "synder sng-player stereo",
                              "synder tracker",
                              "synth dream",
                              "synthesis",
                              "syntracker",
                              "tcb tracker",
                              "tfm music maker",
                              "tfmx",
                              "tfmx st",
                              "the 0ok amazing synth tracker",
                              "the holy noise",
                              "the musical enlightenment",
                              "thomas hermann",
                              "tomy tracker",
                              "tss",
                              "tunefish",
                              "unique development",
                              "unis 669",
                              "velvet studio",
                              "vgm music maker",
                              "vic-tracker",
                              "voodoo supreme synthesizer",
                              "wally beben",
                              "x-tracker",
                              "zoundmonitor"};

const char *other_formats[] = {
    "fasttracker 2",
    "fasttracker",
    "impulsetracker",
    "screamtracker 3",
    "nintendo ds sound format",
    "nintendo sound format",
    "s98",
    "sc68",
    "screamtracker 2",
    "megadrive cym",
    "megadrive gym",

    "mikmod unitrk",
    "multitracker",

    "ay amadeus",
    "ay emul",
    "ay strc",

    "ultratracker",

    "v2",

    "capcom q-sound format",
    "playstation sound format",
    "spectrum asc sound master",
    "spectrum fast tracker",
    "spectrum flash tracker",
    "spectrum fuxoft ay language",
    "spectrum global tracker",
    "spectrum pro sound creator",
    "spectrum pro sound maker",
    "spectrum pro tracker 1",
    "spectrum pro tracker 2",
    "spectrum pro tracker 3",
    "spectrum sound tracker 1.1",
    "spectrum sound tracker 1.3",
    "spectrum sound tracker pro 2",
    "spectrum sound tracker pro",
    "spectrum sq tracker",
    "spectrum st song compiler",
    "spectrum vortex",
    "spectrum vortex tracker ii",
    "spectrum zxs",
    "super nintendo sound format",
    "ultra64 sound format",
    "bbc micro",
    "colecovision",
    "gameboy sound format",
    "gameboy sound system",
    "gameboy sound system gbr",
    "gameboy tracker",
    "sega 32x",
    "sega game gear",
    "sega master system",
    "sega mega cd",
    "sega megadrive",
    "sega sc-3000",
    "sega sg-1000",
    "vectrex",
    "ym",
    "ymst",
    "wonderswan",
    "commodore 64",
    "super nintendo",
    "atari st",
    "atari 8bit",
    "mp3",
    "dreamcast sound format",
};
